# Generated by Django 5.0.7 on 2024-07-19 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('RAM', models.IntegerField()),
                ('ROM', models.IntegerField()),
                ('battery', models.IntegerField()),
                ('OS', models.CharField(max_length=50)),
                ('network', models.CharField(max_length=50)),
                ('primary_cam', models.DecimalField(decimal_places=2, max_digits=5)),
                ('secondary_cam', models.DecimalField(decimal_places=2, max_digits=5)),
                ('processor', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
