# Generated by Django 5.0.7 on 2024-07-19 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='OS',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='RAM',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='ROM',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='battery',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='network',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='price',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='primary_cam',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='secondary_cam',
            field=models.CharField(max_length=100),
        ),
    ]
